In [1]:
import numpy as np
import math
from scipy.spatial.transform import Rotation as R

13. (5 баллов) Первая камера повернута относительно второй на 45 градусов по оси z и   
сдвинута на 10 вдоль направления оси x второй камеры. У обеих камер матрицы   
внутренних параметров единичные. Найти и распечатать фундаментальную   
матрицу.

In [2]:
anglez = math.radians(45)
r = R.from_rotvec([0,0,anglez]).as_matrix()
r

array([[ 0.70710678, -0.70710678,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [3]:
tx = np.array([[0, 0, 0],
               [0, 0, -10],
               [0, 10, 0]])

Tx = np.dot(tx, r)
Tx

array([[  0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        , -10.        ],
       [  7.07106781,   7.07106781,   0.        ]])

In [4]:
F = Tx @ r
F

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -1.00000000e+01],
       [ 1.00000000e+01, -1.77635684e-15,  0.00000000e+00]])

Проверка решения

In [5]:
det = np.linalg.det(F)
det

0.0

In [6]:
rank = np.linalg.matrix_rank(F)
rank

2

14. (5 баллов) Первая камера повернута относительно мировой системы координат на   
45 градусов по оси z, а вторая – на -45 градусов по оси у и сдвинута на 10 в   
направлении оси x. У обеих камер матрицы внутренних параметров единичные.   
Найти и распечатать фундаментальную матрицу

In [7]:
anglez = math.radians(-45)
angley = math.radians(-45)
r = R.from_rotvec([0,0,anglez]).as_matrix() @ R.from_rotvec([0,angley,0]).as_matrix()

tx = np.array([[0, 0, 0],
               [0, 0, -10],
               [0, 10, 0]])
Tx = np.dot(tx, r)
Tx

array([[ 0.        ,  0.        ,  0.        ],
       [-7.07106781,  0.        , -7.07106781],
       [-5.        ,  7.07106781,  5.        ]])

In [8]:
F = Tx @ r
F

array([[ 0.        ,  0.        ,  0.        ],
       [-8.53553391, -5.        , -1.46446609],
       [-2.5       ,  1.46446609,  9.57106781]])

In [9]:
det = np.linalg.det(F)
det

0.0

In [10]:
rank = np.linalg.matrix_rank(F)
rank

2

15. В задаче 14 найти и распечатать оба эпиполя

Эпиполь - проекция центра камеры на изображение другой камеры

In [11]:
anglez = math.radians(45)
P1 = np.eye(3) @ np.c_[R.from_rotvec([0,0,anglez]).as_matrix(), np.array([0, 0, 0])]
P2 = np.eye(3) @ np.c_[R.from_rotvec([0,angley,0]).as_matrix(), np.array([10, 0, 0])]

In [12]:
U, S, Vt = np.linalg.svd(P1)
center1 = Vt[-1]
center1

array([0., 0., 0., 1.])

In [13]:
P1 @ center1

array([0., 0., 0.])

In [14]:
U, S, Vt = np.linalg.svd(P2)
center2 = Vt[-1]
center2 = center2 / center2[3]
center2

array([-7.07106781e+00,  1.61065640e-15,  7.07106781e+00,  1.00000000e+00])

In [15]:
np.around(P2 @ center2, 3)

array([ 0.,  0., -0.])

Ответ:

In [16]:
e1 = P2 @ center1
e1

array([10.,  0.,  0.])

In [17]:
e2 = P1 @ center2
e2

array([-5.        , -5.        ,  7.07106781])

16. В задаче 14 найти и распечатать эпиполярную линию, проходящую через точку
`(0,0)` на первом изображении, и соответствующую ей линию на втором
изображении.

In [18]:
l2 = F @ np.array([0, 0, 1])
l2

array([ 0.        , -1.46446609,  9.57106781])

In [19]:
l1 = e1 * np.array([0, 0, 1])
l1

array([0., 0., 0.])